name: Skein & Stitch - Local
values:
  - key: baseUrl
    value: 'http://localhost:3000'
    type: default
    enabled: true
  - key: adminToken
    value: ''
    type: secret
    enabled: true
  - key: productSlug
    value: ''
    type: default
    enabled: true
  - key: createdProductId
    value: ''
    type: default
    enabled: true
